defmodule Localize.Number.DecimalConformanceTest do
  @moduledoc """
  CLDR 49's decimal format conformance suite (`common/testData/decimal`).

  The fixtures are generated by `org.unicode.cldr.tool.GenerateDecimalFormatTestData`
  from ICU's `NumberFormatter` with **no explicit precision**. That matters:
  `NumberFormatter`'s default is up to six fraction digits, where the CLDR
  decimal *pattern* (`#,##0.###`) allows three. Running these fixtures against
  our pattern defaults produces thousands of mismatches that are about which
  default is in play rather than about formatting, so the standard dimensions
  pass `max_fractional_digits: 6` to match the generator. Compact notation
  carries ICU's own compact precision and takes no override.
  """

  use ExUnit.Case, async: true

  @moduletag :conformance
  @moduletag timeout: 600_000

  # Cases where CLDR's own data and ICU's `NumberFormatter` disagree, and we
  # follow CLDR. These are not counted as failures: the suite is generated
  # from ICU, so where the two conflict it records ICU's answer, and our
  # position is that the format CLDR ships is the one to honour. Each entry
  # below names what CLDR says, so any of them can be checked.
  #
  #   * `scientific` in `gu`, `hi`, `hi-Latn`, `lo`, `mr`, `pa`, `si` — CLDR
  #     gives these locales the scientific pattern `[#E0]`, brackets and all,
  #     so we render "[1.2E0]". `NumberFormatter.notation(scientific())`
  #     ignores the locale pattern and builds the notation itself.
  #   * `ur` percent — CLDR's `symbols-numberSystem-latn` for `ur` sets
  #     `percentSign` to `٪` (U+066A). The generator formats percent as a
  #     measure unit instead, and `ur`'s unit pattern is `{0}%`.
  #   * `gl` grouping — CLDR's `gl` group separator is U+00A0; ICU emits ".".
  #   * `bn` compact long — the pattern is `00000 কোটি`, which carries no
  #     grouping; ICU applies the locale's standard grouping to the mantissa.
  #   * `af` compact short — the pattern is `0 m'.'`, whose quoted literal is
  #     a full stop, so "1,2 m."; ICU drops it.
  #   * `en-IN` and `hi-Latn` compact long — CLDR gives both `0 million`;
  #     ICU renders "12 lakh".
  #   * `ig`, `ps`, `ta` compact — CLDR ships localised patterns (`0 nde`,
  #     `0 میلیونه`, `0M`) that ICU does not use, falling back to the root
  #     forms or to no compact form at all.
  #
  # The count is asserted, not just the membership: if a divergence is
  # resolved upstream, or a new one appears inside one of these dimensions,
  # the number moves and the test says so.
  @divergences %{
    {"af", "decimal", "short"} => 1,
    {"bn", "decimal", "long"} => 6,
    {"en_IN", "decimal", "long"} => 1,
    {"gl", "decimal", ""} => 2,
    {"gl", "percent", ""} => 2,
    {"gu", "scientific", ""} => 5,
    {"hi", "scientific", ""} => 5,
    {"hi_Latn", "decimal", "long"} => 1,
    {"hi_Latn", "scientific", ""} => 5,
    {"ig", "decimal", "long"} => 2,
    {"lo", "scientific", ""} => 5,
    {"mr", "scientific", ""} => 5,
    {"pa", "scientific", ""} => 5,
    {"ps", "decimal", "long"} => 2,
    {"ps", "decimal", "short"} => 2,
    {"si", "scientific", ""} => 5,
    {"ta", "decimal", "short"} => 2,
    {"ur", "percent", ""} => 5
  }

  @files [
    "decimal_test_data.tsv",
    "decimal_modern_locales_test_data.tsv",
    "decimal_extended_numbers_test_data.tsv"
  ]

  defp options("decimal", ""), do: [max_fractional_digits: 6]
  defp options("percent", ""), do: [format: :percent, max_fractional_digits: 6]
  defp options("scientific", ""), do: [format: :scientific, max_fractional_digits: 6]
  defp options("decimal", "short"), do: [format: :short]
  defp options("decimal", "long"), do: [format: :long]
  defp options(_format, _length), do: nil

  defp rows(file) do
    [__DIR__, "..", "..", "support", "data", file]
    |> Path.join()
    |> File.stream!()
    |> Stream.drop(1)
    |> Stream.map(&(&1 |> String.trim_trailing("\n") |> String.split("\t")))
    |> Enum.filter(&match?([_, _, _, _, _], &1))
  end

  for file <- @files do
    @file_name file

    test "#{file} conforms" do
      {failures, diverged} =
        @file_name
        |> rows()
        |> Enum.reduce({[], %{}}, fn [locale, format, length, input, expected],
                                     {failures, diverged} ->
          case options(format, length) do
            nil ->
              {failures, diverged}

            options ->
              cldr_locale = String.replace(locale, "_", "-")
              number = String.to_float(input)

              case Localize.Number.to_string(number, [locale: cldr_locale] ++ options) do
                {:ok, ^expected} ->
                  {failures, diverged}

                other ->
                  key = {locale, format, length}

                  if Map.has_key?(@divergences, key) do
                    {failures, Map.update(diverged, key, 1, &(&1 + 1))}
                  else
                    {[{locale, format, length, input, expected, other} | failures], diverged}
                  end
              end
          end
        end)

      assert failures == [], format_failures(failures)

      for {key, count} <- diverged do
        assert count == @divergences[key],
               "#{inspect(key)} diverges from ICU in #{count} cases, expected " <>
                 "#{@divergences[key]}. A divergence that changes size needs re-checking " <>
                 "against what CLDR ships — see the notes on @divergences."
      end
    end
  end

  defp format_failures(failures) do
    sample =
      failures
      |> Enum.take(10)
      |> Enum.map_join("\n", fn {locale, format, length, input, expected, got} ->
        "  #{locale} #{format}/#{length} #{input}: " <>
          "expected #{inspect(expected)}, got #{inspect(got)}"
      end)

    "#{length(failures)} mismatches:\n#{sample}"
  end
end
