defmodule Localize.Number.DecimalConformanceTest do
  @moduledoc """
  CLDR 49's decimal format conformance suite (`common/testData/decimal`).

  The fixtures are generated by `org.unicode.cldr.tool.GenerateDecimalFormatTestData`
  from ICU's `NumberFormatter` with **no explicit precision**. That matters:
  `NumberFormatter`'s default is up to six fraction digits, where the CLDR
  decimal *pattern* (`#,##0.###`) allows three. Running these fixtures against
  our pattern defaults produces thousands of mismatches that are about which
  default is in play rather than about formatting, so the standard dimensions
  pass `max_fractional_digits: 6` to match the generator. Compact notation
  carries ICU's own compact precision and takes no override.
  """

  use ExUnit.Case, async: true

  @moduletag :conformance
  @moduletag timeout: 600_000

  # Thresholds are ratchets, not targets. Each is the count that survives
  # today; lower them as fixes land and never raise one to make a change fit.
  # Remaining classes, all confirmed against the fixtures:
  #
  #   * negative zero — `-0.0` must keep its sign (`-0`), we drop it
  #   * scientific — the mantissa ignores `max_fractional_digits`
  #   * compact — needs two significant digits, half-even rounding, and a
  #     magnitude re-check after rounding (`-999.9` short is `-1 thousand`,
  #     not `-1,000`)
  @files [
    {"decimal_test_data.tsv", 22},
    {"decimal_modern_locales_test_data.tsv", 262},
    {"decimal_extended_numbers_test_data.tsv", 921}
  ]

  defp options("decimal", ""), do: [max_fractional_digits: 6]
  defp options("percent", ""), do: [format: :percent, max_fractional_digits: 6]
  defp options("scientific", ""), do: [format: :scientific, max_fractional_digits: 6]
  defp options("decimal", "short"), do: [format: :short]
  defp options("decimal", "long"), do: [format: :long]
  defp options(_format, _length), do: nil

  defp rows(file) do
    [__DIR__, "..", "..", "support", "data", file]
    |> Path.join()
    |> File.stream!()
    |> Stream.drop(1)
    |> Stream.map(&(&1 |> String.trim_trailing("\n") |> String.split("\t")))
    |> Enum.filter(&match?([_, _, _, _, _], &1))
  end

  for {file, threshold} <- @files do
    @file_name file
    @threshold threshold

    test "#{file} formats within #{threshold} known mismatches" do
      failures =
        @file_name
        |> rows()
        |> Enum.reduce([], fn [locale, format, length, input, expected], failures ->
          case options(format, length) do
            nil ->
              failures

            options ->
              locale = String.replace(locale, "_", "-")
              number = String.to_float(input)

              case Localize.Number.to_string(number, [locale: locale] ++ options) do
                {:ok, ^expected} -> failures
                other -> [{locale, format, length, input, expected, other} | failures]
              end
          end
        end)

      count = length(failures)

      if count > @threshold do
        sample =
          failures
          |> Enum.take(10)
          |> Enum.map_join("\n", fn {locale, format, length, input, expected, got} ->
            "  #{locale} #{format}/#{length} #{input}: " <>
              "expected #{inspect(expected)}, got #{inspect(got)}"
          end)

        flunk(
          "#{count} mismatches in #{@file_name} exceeds the #{@threshold} " <>
            "known failures.\n#{sample}"
        )
      end
    end
  end
end
