defmodule Localize.Number.DecimalConformanceTest do
  @moduledoc """
  CLDR 49's decimal format conformance suite (`common/testData/decimal`).

  The fixtures are generated by `org.unicode.cldr.tool.GenerateDecimalFormatTestData`
  from ICU's `NumberFormatter` with **no explicit precision**. That matters:
  `NumberFormatter`'s default is up to six fraction digits, where the CLDR
  decimal *pattern* (`#,##0.###`) allows three. Running these fixtures against
  our pattern defaults produces thousands of mismatches that are about which
  default is in play rather than about formatting, so the standard dimensions
  pass `max_fractional_digits: 6` to match the generator. Compact notation
  carries ICU's own compact precision and takes no override.
  """

  use ExUnit.Case, async: true

  @moduletag :conformance
  @moduletag timeout: 600_000

  # Thresholds are ratchets, not targets. Each is the count that survives
  # today; lower them as fixes land and never raise one to make a change fit.
  # 8,857 of 8,925 pass. What remains, in descending order:
  #
  #   * 35 scientific cases in locales whose CLDR scientific pattern is
  #     literally `[#E0]` — `hi`, `gu` and others. We apply the locale's
  #     pattern and produce "[1.2E0]"; ICU's `NumberFormatter.notation(
  #     scientific())` ignores the pattern and builds the notation itself.
  #     That is a difference between two APIs rather than a defect here, and
  #     honouring the data CLDR ships is the defensible side of it.
  #   * Indic compact grouping (`bn` long) and a handful of compact plural
  #     and abbreviation differences (`af`, `bs`, `en-IN`).
  #   * `gl` grouping separator and the `ur` percent sign, which look like
  #     symbol-selection questions rather than formatting ones.
  @files [
    {"decimal_test_data.tsv", 0},
    {"decimal_modern_locales_test_data.tsv", 62},
    {"decimal_extended_numbers_test_data.tsv", 6}
  ]

  defp options("decimal", ""), do: [max_fractional_digits: 6]
  defp options("percent", ""), do: [format: :percent, max_fractional_digits: 6]
  defp options("scientific", ""), do: [format: :scientific, max_fractional_digits: 6]
  defp options("decimal", "short"), do: [format: :short]
  defp options("decimal", "long"), do: [format: :long]
  defp options(_format, _length), do: nil

  defp rows(file) do
    [__DIR__, "..", "..", "support", "data", file]
    |> Path.join()
    |> File.stream!()
    |> Stream.drop(1)
    |> Stream.map(&(&1 |> String.trim_trailing("\n") |> String.split("\t")))
    |> Enum.filter(&match?([_, _, _, _, _], &1))
  end

  for {file, threshold} <- @files do
    @file_name file
    @threshold threshold

    test "#{file} formats within #{threshold} known mismatches" do
      failures =
        @file_name
        |> rows()
        |> Enum.reduce([], fn [locale, format, length, input, expected], failures ->
          case options(format, length) do
            nil ->
              failures

            options ->
              locale = String.replace(locale, "_", "-")
              number = String.to_float(input)

              case Localize.Number.to_string(number, [locale: locale] ++ options) do
                {:ok, ^expected} -> failures
                other -> [{locale, format, length, input, expected, other} | failures]
              end
          end
        end)

      count = length(failures)

      if count > @threshold do
        sample =
          failures
          |> Enum.take(10)
          |> Enum.map_join("\n", fn {locale, format, length, input, expected, got} ->
            "  #{locale} #{format}/#{length} #{input}: " <>
              "expected #{inspect(expected)}, got #{inspect(got)}"
          end)

        flunk(
          "#{count} mismatches in #{@file_name} exceeds the #{@threshold} " <>
            "known failures.\n#{sample}"
        )
      end
    end
  end
end
