defmodule Mix.Tasks.Localize.Unit.GenConversionsTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  alias Mix.Tasks.Localize.Unit.GenConversions

  # Values spanning the range a conversion could plausibly go wrong over,
  # including 0 (which only an offset unit distinguishes) and a large value
  # (which a saturating scale would fail).
  @values [0, 1, 2.5, 7, 30, 100, 1000]

  # The derived compounds a robotics caller asked for and could not get from
  # the earlier quantity-selected table. CLDR lists none of them under any
  # quantity, but every one is convertible.
  @derived ~w(
    newton-meter kilogram-square-meter meter-per-square-second
    degree-per-square-meter radian-per-square-meter
    newton-meter-second-per-degree newton-meter-second-per-radian
    degree-per-second radian-per-second
  )

  # Generating and compiling the module is by far the expensive part of these
  # tests, and the task takes no arguments that vary its output, so one module
  # serves every case. The compiler's own output is captured here rather than
  # in a test because a second compile would only report redefinition.
  setup_all do
    directory =
      Path.join(System.tmp_dir!(), "gen_conversions_#{System.unique_integer([:positive])}")

    File.mkdir_p!(directory)
    path = Path.join(directory, "units.ex")

    Mix.shell(Mix.Shell.Process)
    GenConversions.run(["--module", "GenTest.Units", "--output", path])
    Mix.shell(Mix.Shell.IO)

    {modules, diagnostics} = with_io(:stderr, fn -> Code.compile_file(path) end)

    on_exit(fn -> File.rm_rf!(directory) end)

    {:ok,
     units: GenTest.Units,
     path: path,
     source: File.read!(path),
     bytecode: modules,
     diagnostics: diagnostics}
  end

  describe "the generated module" do
    test "compiles without a single warning", %{diagnostics: diagnostics} do
      # The caller commits this file and compiles it in their own project,
      # very possibly with --warnings-as-errors. NimbleParsec's output warns
      # in several ways once written out as source rather than expanded from
      # AST, and every one of those has to be dealt with by the generator.
      assert diagnostics == ""
    end

    test "calls nothing outside itself and OTP", %{bytecode: bytecode} do
      # The whole point is a module that compiles and runs on a target where
      # Localize is not there at all, so the check is on what the compiled
      # code actually calls rather than on what the source mentions — the
      # moduledoc names `Localize.Unit`, and prose cannot be a dependency.
      own = Enum.map(bytecode, fn {module, _binary} -> module end)

      external =
        for {_module, binary} <- bytecode,
            {:ok, {_module, [imports: imports]}} = :beam_lib.chunks(binary, [:imports]),
            {called, _function, _arity} <- imports,
            called not in own,
            uniq: true,
            do: called

      assert Enum.filter(
               external,
               &(&1 |> Atom.to_string() |> String.starts_with?("Elixir.Localize"))
             ) ==
               []

      refute NimbleParsec in external
    end

    test "records nothing that varies between runs", %{source: source} do
      # The header promises that regenerating on the same CLDR data reproduces
      # the same file, so nothing may capture the run itself.
      refute source =~ ~r/Generated at/
      refute source =~ System.tmp_dir!()
    end

    test "is regenerated byte for byte identically", %{source: source} do
      directory = Path.join(System.tmp_dir!(), "regen_#{System.unique_integer([:positive])}")
      File.mkdir_p!(directory)
      path = Path.join(directory, "units.ex")

      Mix.shell(Mix.Shell.Process)
      GenConversions.run(["--module", "GenTest.Units", "--output", path])

      # The task swaps the shell out while nimble_parsec runs; it has to put
      # the caller's back, or its own report goes to the terminal instead of
      # wherever the caller was collecting it.
      assert_received {:mix_shell, :info, [message]}
      assert IO.iodata_to_binary(message) =~ path

      assert_received {:mix_shell, :info, [summary]}
      assert summary =~ ~r/155 units, \d+ spellings/

      Mix.shell(Mix.Shell.IO)

      assert File.read!(path) == source

      File.rm_rf!(directory)
    end
  end

  describe "agreement with Localize" do
    test "every unit CLDR defines a conversion for", %{units: units} do
      defined = Localize.Unit.known_units_by_category() |> Map.values() |> List.flatten()

      assert length(defined) > 100

      for unit <- defined, unit != "beaufort", value <- @values do
        assert_agrees(units, unit, value)
      end
    end

    test "the derived compounds no quantity lists", %{units: units} do
      for unit <- @derived, value <- @values do
        assert_agrees(units, unit, value)
      end
    end

    test "SI-prefixed units", %{units: units} do
      prefixed =
        for prefix <- ~w(milli kilo micro nano mega giga centi hecto femto tera),
            base <- ~w(meter second gram watt joule newton pascal hertz volt ampere liter),
            do: prefix <> base

      for unit <- prefixed, value <- @values, do: assert_agrees(units, unit, value)
    end

    test "powers and per-compounds", %{units: units} do
      powers =
        for power <- ~w(square cubic pow4),
            base <- ~w(meter kilometer millimeter foot second),
            do: power <> "-" <> base

      compounds =
        for numerator <- ~w(meter kilometer newton joule watt gram),
            denominator <- ~w(second hour square-second cubic-meter kilogram),
            do: numerator <> "-per-" <> denominator

      for unit <- powers ++ compounds, value <- @values, do: assert_agrees(units, unit, value)
    end

    test "base units are canonical, not merely equivalent", %{units: units} do
      # An equivalent-but-differently-spelled base would still convert
      # correctly and yet be useless for comparing two results.
      for unit <- @derived ++ ~w(kilometer-per-hour celsius newton pound-force) do
        assert {:ok, {_value, base}} = units.to_base(1, unit)
        assert {:ok, expected} = Localize.Unit.BaseUnit.base_unit(unit)

        assert base == to_string(expected),
               "#{unit} resolved to #{base}, Localize says #{expected}"
      end
    end
  end

  describe "unit spellings" do
    test "resolves identifiers, spaced names, symbols and plurals alike", %{units: units} do
      canonical = units.to_base(30, "kilometer-per-hour")

      for spelling <- ["kilometers per hour", "km/h", "KM/H", "  kilometer-per-hour  "] do
        assert units.to_base(30, spelling) == canonical, "#{spelling} did not resolve"
      end
    end

    test "an unknown unit is an error, not a crash", %{units: units} do
      # "furlong-per-fortnight" would not do: CLDR knows both halves, so it
      # converts. A name has to be invented to be unknown.
      assert {:error, {:unknown_unit, "zorkmid-per-blorb"}} =
               units.to_base(1, "zorkmid-per-blorb")

      assert {:error, {:unknown_unit, ""}} = units.to_base(1, "")
      assert {:ok, _furlongs_per_fortnight} = units.to_base(1, "furlong-per-fortnight")
    end
  end

  describe "offset and non-affine units" do
    test "an offset unit converts, carrying its offset", %{units: units} do
      assert {:ok, {373.15, "kelvin"}} = units.to_base(100, "celsius")
      assert {:ok, {373.15, "kelvin"}} = units.to_base(212, "fahrenheit")
      assert {:ok, {+0.0, "kelvin"}} = units.to_base(0, "kelvin")
    end

    test "the offset is dropped by a prefix or a compound, as Localize drops it", %{units: units} do
      # A prefixed or compounded temperature is a scale, not an affine
      # temperature, and carries no zero point. Getting this wrong is
      # invisible — the value is merely off by 273.15.
      assert {:ok, {1000.0, "kelvin"}} = units.to_base(1, "kilocelsius")
      assert {:ok, {1.0, "kelvin-per-second"}} = units.to_base(3600, "celsius-per-hour")

      # A power keeps it, which is the one case that reads the other way.
      assert {:ok, {274.15, "square-kelvin"}} = units.to_base(1, "square-celsius")

      for unit <- ~w(kilocelsius millicelsius kilofahrenheit square-celsius
                     celsius-per-hour celsius-per-second meter-celsius),
          value <- @values do
        assert_agrees(units, unit, value)
      end
    end

    test "a non-affine unit is refused rather than approximated", %{units: units} do
      # Beaufort saturates, so no factor and offset can represent it. Localize
      # itself converts it, through a scale this module cannot express.
      assert {:error, {:unknown_unit, "beaufort"}} = units.to_base(5, "beaufort")
      assert {:ok, 9.4} = Localize.Unit.Conversion.convert(5, "beaufort", "meter-per-second")
    end
  end

  describe "the ~u sigil" do
    test "resolves a literal at compile time", %{units: units} do
      source = """
      defmodule GenTest.SigilUser do
        import #{inspect(units)}

        def speed, do: ~u"30 kilometers per hour"
        def torque, do: ~u"2.5 newton-meter"
        def boiling, do: ~u"100 celsius"
      end
      """

      [{compiled, _bytecode} | _rest] = Code.compile_string(source)

      assert {8.333333333333334, "meter-per-second"} = compiled.speed()
      assert {2.5, "kilogram-square-meter-per-square-second"} = compiled.torque()
      assert {373.15, "kelvin"} = compiled.boiling()
    end

    test "refuses an interpolated literal", %{units: units} do
      source = """
      defmodule GenTest.SigilInterpolated do
        import #{inspect(units)}

        def bad(value), do: ~u"\#{value} meter"
      end
      """

      assert_raise ArgumentError, ~r/resolves at compile time/, fn ->
        Code.compile_string(source)
      end
    end

    test "refuses an unknown unit at compile time", %{units: units} do
      source = """
      defmodule GenTest.SigilUnknown do
        import #{inspect(units)}

        def bad, do: ~u"1 zorkmid-per-blorb"
      end
      """

      assert_raise ArgumentError, ~r/unknown unit/, fn ->
        Code.compile_string(source)
      end
    end
  end

  describe "known_units/0" do
    test "reports the tabulated units", %{units: units} do
      units = units.known_units()

      assert length(units) > 100
      assert "meter" in units
      assert "celsius" in units
    end

    test "is a floor, not the accepted set", %{units: units} do
      refute "millinewton" in units.known_units()
      assert {:ok, {1.0, "kilogram-meter-per-square-second"}} = units.to_base(1000, "millinewton")
    end
  end

  describe "task arguments" do
    test "explains the options that selection used to need" do
      for retired <- ~w(--types --units --list) do
        assert_raise Mix.Error, ~r/no longer needed/, fn ->
          GenConversions.run([retired, "speed"])
        end
      end
    end

    test "rejects an unknown option" do
      assert_raise OptionParser.ParseError, fn ->
        GenConversions.run(["--nonsense"])
      end
    end
  end

  defp assert_agrees(units, unit, value) do
    assert {:ok, {actual, base}} = units.to_base(value, unit), "#{unit} did not resolve"
    assert {:ok, localize_base} = Localize.Unit.BaseUnit.base_unit(unit)

    assert base == to_string(localize_base),
           "#{unit} resolved to #{inspect(base)}, Localize says #{inspect(localize_base)}"

    # A unit whose dimensions cancel — "gram-per-kilogram" — has "" as its base
    # unit, and Localize will not convert into that. The base agreeing is all
    # there is to check for those.
    if base != "" do
      assert {:ok, expected} = Localize.Unit.Conversion.convert(value, unit, base)

      assert_in_delta actual,
                      expected,
                      max(abs(expected) * 1.0e-9, 1.0e-9),
                      "#{value} #{unit}: generated #{actual}, Localize #{expected}"
    end
  end
end
